### ISSUE TITLE
Unable to compile with OpenJDK 1.7.0_95

### ISSUE THREAD

**Issue by bweir** [peteroid/crux-compiler#1]
Hi there,

I followed the instructions on your README and this was the result.

```
$ javac crux/*.java ast/*.java types/*.java mips/*.java
crux/Scanner.java:8: error: class, interface, or enum expected
	public static String studentName = "TODO: YOUR NAME";
	              ^
crux/Scanner.java:9: error: class, interface, or enum expected
	public static String studentID = "TODO: Your 8-digit id";
	              ^
crux/Scanner.java:10: error: class, interface, or enum expected
	public static String uciNetID = "TODO: uci-net id";
	              ^
3 errors
```

Can you tell me why this is happening? Is there a dependency on Oracle JDK? If so, can you modify your code to work on OpenJDK?

**Comment by peteroid** [comment]
Thanks for the noticing! That's my mistake to put the strings declaration outside of the class declaration. That should not be the problem of the SDK dependency.

**Comment by bweir** [comment]
Oh ok, well, can you fix it so I can run it?
On May 1, 2016 2:25 AM, "PETEroid" <notifications@github.com> wrote:

Thanks for the noticing! That's my mistake to put the strings declaration
outside of the class declaration. That should not be the problem of the SDK
dependency.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/peteroid/crux-compiler/issues/1#issuecomment-216030454>

**Comment by peteroid** [comment]
You could checkout the head: 89607df89e3774cde2d509b0bf36eac9b9812493
